apiVersion: argoproj.io/v1alpha1  
kind: ApplicationSet  
metadata:  
  name: notes-app  
spec:  
  generators:  
    - git:  
        repoURL: https://github.com/kirillyesikov/pipelineDEMO.git  
        revision: HEAD  
        files:  
        - path: "configs/git-generator-files-discovery/cluster-config/**/config.json"  
  template:  
    metadata:  
      name: '{{cluster.namespace}}-notes-app'  
    spec:  
      project: ARGO_PROJECT_ID  
      source:  
        repoURL: https://github.com/kirillyesikov/pipelineDEMO.git  
        targetRevision: HEAD  
        path: "deployment"  
      destination:  
        server: '{{cluster.address}}'  
        namespace: '{{cluster.namespace}}'  
      syncPolicy:  
        syncOptions:
        - CreateNamespace=true
