---
# Source: gitops-helm/templates/gitops-agent/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: gitops-agent
  namespace: "argocd"
  labels:
    helm.sh/chart: gitops-helm-1.1.10
    app.kubernetes.io/name: harness-gitops-agent
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: gitops-agent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: harness-gitops
    app.kubernetes.io/version: "v0.81.0"
---
# Source: gitops-helm/templates/upgrader/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-agent-upgrader
  namespace: "argocd"
  labels:
    helm.sh/chart: gitops-helm-1.1.10
    app.kubernetes.io/name: harness-gitops-agent-upgrader
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: gitops-agent-upgrader
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: harness-gitops
    app.kubernetes.io/version: "v0.81.0"
---
# Source: gitops-helm/templates/gitops-agent/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    helm.sh/chart: gitops-helm-1.1.10
    app.kubernetes.io/name: harness-agent-secret
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: gitops-agent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: harness-gitops
    app.kubernetes.io/version: "v0.81.0"
  name: gitops-agent
  namespace: argocd
type: Opaque
stringData:
  GITOPS_AGENT_TOKEN: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFd0FJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLb3dnZ1NtQWdFQUFvSUJBUUNzNERZTlp1Z2s4a0JTCngzZkpTYy9ZemxqN3p6d09MQ094WSthd1oxWkpDRmVlc04yWDhsd2Nyb0VtR01YNzVvSi9TZ3hQOG9LWjkraEMKc0FqR0FJOXBTSkt5elVYdzZsS05CWnh4aHFKTjRxUXdDNzIvYWIwbVgxSDRzc2ZGMS9FQlBkL3pkYkZ1VUdadwpXVG9HbzlSU2dtTkhXcEdabDBNMFBDTE42WCtlN3d1KzJUMmx4OUROb3RqNG84bVdIeVV2bTM1RjBJZkhLQllXCkZuUVZjQUQwZWk2NVhDZkRLdDkxQ1crdjlHMWYyTUxlUUxSTEtpeUV1WWduRG93dTduNG4za2lwTUtkdkVGOFIKQTlhbHdJUk9zd0RRWmIyTGkvcGdraUptdStTYkIydndaTlYzNmRxU0dyWk44Q1RpQSt6N294Znl4aldtNXdxagpXL09QNWFaaEFnTUJBQUVDZ2dFQkFJSjBRM1hEbFNUa1JoUHhmL3crbmdEK1hmblBmWU00WGNyc0YxWkE5TVR4CjdhVEwxTHhuNElpb1NyOGo3S3RWWEY2UDAxQzFNVWJjNDhFSE0rZXUzb25WZ1JZNmZ5LzRzMGpGMWpONUpKdGYKandUT3AyWjlkWVl5WWhvcFYwVjkyZGxWQnQyaWo3MHVJTTloRmIrUys1TXozNVVsekQrNS9MVzdONHhwU3F2MApmRWhvQk83MkFSYmM5YTFPNDZsMWRXWEV1cDZTcGdKNFA4MnpVdGw1Vk9tMEduVjlGRjBnMnc2TmoveWRqbk9tCk9MQjVTUTdTZXZtUldkK1IzV3EwbUswSEVEcytqSDl5amhtdmd3RUxsMjVjUkozNjR4cENqVFRZK1BVL1BRMkgKbVZFcVJJY3FQbWxINEs2eS9LcktpRzRmN1RkYnZIZkQrUTdwdE9sTGMxRUNnWUVBMGFuVFFwdEdnRnZnaUdleQp4T2lXdlV6OHpzVTZqRHdrWHRwaW84NnI5ek9ESzE4d3JwWEdoSHRlZmpUcHZzVWZsN0dVR20rb3BLNStPbTlTClZ5TmQrZmZsL1pyTTM3L3d6UUJNbGJZdmd0UHVNdmRsQkJwdkZYdWFFOCtkSUQwWGI5UHRyQlBBdlBwbXhCZTcKSXpIVW1FN0w3U3grb2I0R0ltRVB2RWhXSmswQ2dZRUEweFVNTk1Od04xd3dTa3A4eUNkQUtNSHd3WGZVeGxiUgp2YndzNWNwcXM0NUlUdGVVMXhlU2Z6Nk5hTFA5YTNIRTV0K0pDVVl6R29xbUpkbHN1U3BOVXd5dS9tTDVRWGhFCnZBVGFmYjJJZ08yejAxYXNaUlMzSzNrT0hySzlsVlhOU2J6eElWR245S2VieXdzLzUvK3dRNUx6akRMUnI0WDMKRlg4UFRrM2pzbVVDZ1lFQWpjVlM1L2dORFNDVFRFa3FkY0Y4cEZaWm9BdDNVbm9jY2RNajNmWVREQjNWOVU3eApvU3YveDNlUVpyQ3EyZWQ3UEZ6RWM3ZkxCa2hEYkluMzJKbytvcGRBK21KaFpHN3FpZ1JJeFBjalcwaXBDZWVGCmMrZlg4MlBYeE11ZlNMeG1pNlIzVXVNc2NkeXovcWE1VU13U0lFY3YxNWs5cTJyTnhSTnl5M0x5WmdVQ2dZRUEKa3hXd2lyZkE0eUtmRjdWdDIvN1Z5MURSRmM4TmVpT1hSWEh4aXpJUVJnd1lRTEFpSy90bC9ycTB5TWZiQjlxZwpEUXlvcmNpMzVYL0ZwTXdyNFo4amdJSnZFaDRmZDhwNWd0YVM5Vmx6Mi90RytqWUVMTzlSYjc2TDQwSkRydUs2CkNPN2F5NC9kekRKYThoSmx0cURKejF4L3p5cStTR08rTjhGeEJleHFoSzBDZ1lFQW9XeW1NdUo3VTU5amUwOWwKclN3NmRSY3d6eFFSOS83d2NsemRNV3pETHBobnBINkJnQnUrblNwVy9QZnk4TitaUFY0dXhvdlBqZUVScUNINAo1WndvTC9wZnNmd3Z1MzFRU2pqVlJNbnBCV3JEZlZIeGQrUERwV1g4NEo4b0tMbGM0a1VuY01tcFllT3hIQ2ZwCnI3TzRPRFFrVk1GbmhmcHdHSzNHMEdXTFJTUT0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
---
# Source: gitops-helm/templates/gitops-agent/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    helm.sh/chart: gitops-helm-1.1.10
    app.kubernetes.io/name: harness-agent-ssh
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: gitops-agent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: harness-gitops
    app.kubernetes.io/version: "v0.81.0"
  name: gitops-agent-mtls
  namespace: argocd
type: Opaque
data:
  client.crt: |
    
  client.key: |
---
# Source: gitops-helm/templates/gitops-agent/configmap.yaml
apiVersion: v1
data:
  GITOPS_ACCOUNT_IDENTIFIER: n7brygS2SSSMAkd8ntpoYA
  GITOPS_AGENT_IDENTIFIER: gitops
  GITOPS_ORG_IDENTIFIER: default
  GITOPS_PROJECT_IDENTIFIER: ProxMOx
  GITOPS_SERVICE_HTTP_TLS_ENABLED: "false"
  GITOPS_SERVICE_HTTP_CERT_FILES: /tmp/ca.bundle
  GITOPS_SERVICE_MTLS_ENABLED: "false"
  GITOPS_SERVICE_HTTP_CLIENT_CERT: /etc/mtls/client.crt
  GITOPS_SERVICE_HTTP_CLIENT_KEY: /etc/mtls/client.key
  AGENT_HTTP_TARGET: https://app.harness.io/gitops
  GITOPS_SERVICE_PROTOCOL: HTTP1
  GITOPS_AGENT_ENABLE_RECONCILE: "true"
  GITOPS_AGENT_RECONCILE_INTERVAL: "100"
  GITOPS_AGENT_DISCOVER_APPLICATION_PODS_DURATION_IN_SECS: "120"
  LOG_LEVEL: debug
  GITOPS_AGENT_FETCH_TYPE: "POLLER"
  GITOPS_ARGOCD_REPO: argocd-repo-server
  GITOPS_ARGOCD_REDIS: argocd-redis
  GITOPS_ARGOCD_REDIS_HA: redis-ha
  GITOPS_ARGOCD_REDIS_HA_PROXY: redis-ha-haproxy
  GITOPS_ARGOCD_APP_CONTROLLER: argocd-application-controller
  GITOPS_ARGOCD_APPSET_CONTROLLER: argocd-applicationset-controller
  GITOPS_AGENT_AVAILABILITY_MODE: NON-HA
  ARGOCD_SERVER_REPO_SERVER: argocd-repo-server:8081
  REDIS_SERVER: argocd-redis:6379
kind: ConfigMap
metadata:
  labels:
    helm.sh/chart: gitops-helm-1.1.10
    app.kubernetes.io/name: harness-gitops-agent-cm
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: gitops-agent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: harness-gitops
    app.kubernetes.io/version: "v0.81.0"
  name: gitops-agent
  namespace: argocd
---
# Source: gitops-helm/templates/upgrader/harness-upgrader-cm.yaml
apiVersion: v1
data:
  UPGRADER_GITOPS_ACCOUNT_IDENTIFIER: n7brygS2SSSMAkd8ntpoYA
  UPGRADER_GITOPS_AGENT_IDENTIFIER: gitops
  UPGRADER_GITOPS_ORG_IDENTIFIER: default
  UPGRADER_GITOPS_PROJECT_IDENTIFIER: ProxMOx
  UPGRADER_MODE: GitopsAgent
  UPGRADER_NAMESPACE: argocd
  UPGRADER_WORKLOAD_NAME: gitops-agent
  UPGRADER_CONTAINER_NAME: gitops-agent
  UPGRADER_GITOPS_AGENT_HTTP_TARGET: https://app.harness.io/prod1/gitops
  UPGRADER_GITOPS_USE_V2: "true"
  UPGRADER_GITOPS_ALL: "false"
kind: ConfigMap
metadata:
  name: gitops-agent-upgrader
  namespace: "argocd"
---
# Source: gitops-helm/templates/gitops-agent/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitops-agent
  labels:
    helm.sh/chart: gitops-helm-1.1.10
    app.kubernetes.io/name: harness-gitops-agent
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: gitops-agent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: harness-gitops
    app.kubernetes.io/version: "v0.81.0"
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - delete
      - get
      - patch
      - watch
      - list
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
  - apiGroups:
      - argoproj.io
    resources:
      - applications
      - applicationsets
      - appprojects
    verbs:
      - get
      - list
      - update
      - watch
      - create
      - patch
      - delete
  - apiGroups:
      - batch
    resources:
      
      - jobs
    verbs:
      - create
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      
      - create
---
# Source: gitops-helm/templates/gitops-agent/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitops-agent
  labels:
    helm.sh/chart: gitops-helm-1.1.10
    app.kubernetes.io/name: harness-gitops-agent
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: gitops-agent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: harness-gitops
    app.kubernetes.io/version: "v0.81.0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitops-agent
subjects:
- kind: ServiceAccount
  name: gitops-agent
  namespace: argocd
---
# Source: gitops-helm/templates/gitops-agent/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitops-agent
  namespace: "argocd"
  labels:
    helm.sh/chart: gitops-helm-1.1.10
    app.kubernetes.io/name: harness-gitops-agent
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: gitops-agent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: harness-gitops
    app.kubernetes.io/version: "v0.81.0"
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - external-secrets.io
  resources:
    - externalsecrets
  verbs:
    - get
    - list
    - watch
    - update
    - patch
    - delete
    - create
- apiGroups:
    - generators.external-secrets.io
  resources:
    - gcraccesstokens
    - ecrauthorizationtokens
  verbs:
    - get
    - list
    - watch
    - update
    - patch
    - delete
    - create
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - appprojects
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
  - patch
- apiGroups:
  - ""
  resources:
  - events
  - pods
  verbs:
  - create
  - list
  - watch
  - get
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - update
    - patch
---
# Source: gitops-helm/templates/upgrader/role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-agent-upgrader
  namespace: "argocd"
  labels:
    helm.sh/chart: gitops-helm-1.1.10
    app.kubernetes.io/name: harness-gitops-agent-upgrader
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: gitops-agent-upgrader
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: harness-gitops
    app.kubernetes.io/version: "v0.81.0"
rules:
  - apiGroups:
    - batch
    - apps
    - extensions
    resources:
    - cronjobs
    verbs:
    - get
    - list
    - watch
    - update
    - patch
  - apiGroups:
    - extensions
    - apps
    resources:
    - deployments
    - statefulsets
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
---
# Source: gitops-helm/templates/gitops-agent/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitops-agent
  namespace: "argocd"
  labels:
    helm.sh/chart: gitops-helm-1.1.10
    app.kubernetes.io/name: harness-gitops-agent
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: gitops-agent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: harness-gitops
    app.kubernetes.io/version: "v0.81.0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitops-agent
subjects:
- kind: ServiceAccount
  name: gitops-agent
  namespace: argocd
---
# Source: gitops-helm/templates/upgrader/rolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-agent-upgrader
  namespace: "argocd"
  labels:
    helm.sh/chart: gitops-helm-1.1.10
    app.kubernetes.io/name: harness-gitops-agent-upgrader
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: gitops-agent-upgrader
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: harness-gitops
    app.kubernetes.io/version: "v0.81.0"
roleRef:
  kind: Role
  name: gitops-agent-upgrader
  apiGroup: ""
subjects:
  - kind: ServiceAccount
    name: gitops-agent-upgrader
    namespace: "argocd"
---
# Source: gitops-helm/templates/gitops-agent/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-agent
  namespace: "argocd"
  labels:
    helm.sh/chart: gitops-helm-1.1.10
    app.kubernetes.io/name: harness-gitops-agent
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: gitops-agent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: harness-gitops
    app.kubernetes.io/version: "v0.81.0"
spec:
  replicas: 1
  revisionHistoryLimit: 
  selector:
    matchLabels:
      app.kubernetes.io/name: harness-gitops-agent
      app.kubernetes.io/instance: argocd
  template:
    metadata:
      annotations:
      labels:
        helm.sh/chart: gitops-helm-1.1.10
        app.kubernetes.io/name: harness-gitops-agent
        app.kubernetes.io/instance: argocd
        app.kubernetes.io/component: gitops-agent
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: harness-gitops
        app.kubernetes.io/version: "v0.81.0"
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccountName: gitops-agent
      containers:
      - command:
          - /app/agent
        name: gitops-agent
        image: docker.io/harness/gitops-agent:v0.81.0
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: gitops-agent
          - secretRef:
              name: gitops-agent
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: REDIS_USERNAME
            valueFrom:
              secretKeyRef:
                name: argocd-redis
                key: redis-username
                optional: true
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: argocd-redis
                optional: true
                key: auth
          - name: REDIS_SENTINEL_USERNAME
            valueFrom:
              secretKeyRef:
                name: redis-sentinel-username
                key: redis-sentinel-username
                optional: true
          - name: REDIS_SENTINEL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-sentinel-password
                key: redis-sentinel-password
                optional: true
        volumeMounts:
        - mountPath: /app/config/ssh
          name: ssh-known-hosts
        - mountPath: /app/config/tls
          name: tls-certs
        - mountPath: /app/config/server/tls
          name: argocd-repo-server-tls
        - mountPath: /home/argocd
          name: plugins-home
        - mountPath: /tmp
          name: tmp
        - mountPath: /etc/mtls
          name: mtls-certs
        - mountPath: /app/logs
          name: log-volume
        startupProbe:
          exec:
            command:
              - test
              - -s
              - logs/agent.log
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 32
        livenessProbe:
          httpGet:
            path: /healthz?full=true
            port: 8090
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8090
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "1"
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      volumes:
      - name: plugins-home
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      - name: ssh-known-hosts
        configMap:
          name: argocd-ssh-known-hosts-cm
          defaultMode: 420
      - name: tls-certs
        configMap:
          name: argocd-tls-certs-cm
          defaultMode: 420
      - name: argocd-repo-server-tls
        secret:
          secretName: argocd-repo-server-tls
          optional: true
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
          - key: ca.crt
            path: ca.crt
      - name: mtls-certs
        secret:
          secretName: gitops-agent-mtls
          optional: true
          items:
          - key: client.crt
            path: client.crt
          - key: client.key
            path: client.key
      
      - name: log-volume
        emptyDir: { }
      dnsPolicy: ClusterFirst
---
# Source: gitops-helm/templates/upgrader/cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitops-agent-upgrader
  namespace: "argocd"
  labels:
    helm.sh/chart: gitops-helm-1.1.10
    app.kubernetes.io/name: harness-gitops-agent-upgrader
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: gitops-agent-upgrader
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: harness-gitops
    app.kubernetes.io/version: "v0.81.0"
spec:
  schedule: "0 */4 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 20
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: gitops-agent-upgrader
          containers:
            - name: upgrader
              image: docker.io/harness/upgrader:latest
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: gitops-agent-upgrader
              env:
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: UPGRADER_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: GITOPS_AGENT_TOKEN
                      name: gitops-agent
              volumeMounts:
                - name: mtls-certs
                  mountPath: /etc/mtls
                - name: config-volume
                  mountPath: /etc/config
          volumes:
            - name: config-volume
              configMap:
                name: gitops-agent-upgrader
            - name: mtls-certs
              secret:
                secretName: gitops-agent-mtls
                optional: true
                items:
                  - key: client.crt
                    path: client.crt
                  - key: client.key
                    path: client.key
          restartPolicy: Never
