service:
  name: kirill_app
  identifier: kirill_app
  orgIdentifier: default
  projectIdentifier: ProxMOx
  serviceDefinition:
    spec:
      manifests:
        - manifest:
            identifier: gitopsrepo
            type: ReleaseRepo
            spec:
              store:
                type: Github
                spec:
                  connectorRef: kirill_gitconnector
                  gitFetchType: Branch
                  paths:
                    - deployment/<+env.name>/config.json
                  branch: main
        - manifest:
            identifier: gitops
            type: DeploymentRepo
            spec:
              store:
                type: Github
                spec:
                  connectorRef: kirill_gitconnector
                  gitFetchType: Branch
                  paths:
                    - applicationset.yaml
                  branch: main
    type: Kubernetes
  gitOpsEnabled: true
