service:
    name: kirill_app
    identifier: kirillapp
    serviceDefinition:
        type: Kubernetes
        spec:
            manifests:
                - manifest:
                    identifier: app
                    type: K8sManifest
                    spec:
                      store:
                        type: Github
                        spec:
                            connectorRef: kirillgitconnector
                            gitFetchType: Branch
                            paths:
                                - deployment/deployment.yaml 
                                - deployment/service.yaml
                            repoName: pipelineDEMO
                            branch: main
                        skipResourceVersioning: false
                        enableDeclarativeRollback: false
    gitOpsEnabled: true
