metadata:
  name: "notes-app"
  labels:
    app: "notes-app"
apiVersion: "apps/v1"
kind: "Deployment"
asset_id: "null-null"
spec:
  template:
    metadata:
      labels:
        app: "notes-app"
    spec:
      containers:
      - image: "kyesikov/notes-app:null"
        imagePullPolicy: "IfNotPresent"
        imagePullSecrets:
        - name: "kirill"
        name: "notes-app"
        resources:
          requests:
            cpu: "150m"
        ports:
        - containerPort: 3000
  replicas: 2
  selector:
    matchLabels:
      app: "notes-app"
