apiVersion: apps/v1
kind: Deployment
spec:
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-app 
        image: kyesikov/notes-app:null
        imagePullPolicy: IfNotPresent
        imagePullSecrets:
        - name: kirill
        resources:
          requests:
            cpu: 150m
        ports:
        - containerPort: 3000
  replicas: 2
  selector:
    matchLabels:
      app: notes-app
